# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: maven:3.3.9

pipelines:
  default:
    - step:
        name: Build
        script:
          - cd src/main
          - git archive --format=jar main -o logservice-1.0.0.jar
        artifacts:
          - src/main/logservice-1.0.0.jar

    - step:
        name: Deploy to production
        deployment: production
        caches:
          - pip
        script:
          - pipe: atlassian/heroku-deploy:1.2.1
            variables:
              HEROKU_API_KEY: 48f9aa2f-a930-4d1e-8ea3-5ba16e8009c2
              HEROKU_APP_NAME: log-service-ror
              ZIP_FILE: logservice.jar