spring:
  elasticsearch:
    rest:
      username: elastic
      password: 0OUXZO6UKYnkJisGnIm5d8wn
      uris: https://logservice.es.eastus2.azure.elastic-cloud.com:9243
  mvc:
    async:
      request-timeout: 5000
server:
  port: ${PORT:5000}
  servlet:
    context-path: /
app:
  security:
    secret-key: SecretKeyGrizzly
slack:
  token: xoxb-2518902811235-2585938444480-07lV2jkicJ1JGV8PMvwRu5d9
logging.level:
  com.slack.api: DEBUG