spring:
  elasticsearch:
    rest:
      username: elastic
      password: 0OUXZO6UKYnkJisGnIm5d8wn
      uris: https://logservice.es.eastus2.azure.elastic-cloud.com:9243
  mvc:
    async:
      request-timeout: 5000
server:
  port: ${PORT:5000}
  servlet:
    context-path: /
app:
  security:
    secret-key: SecretKeyGrizzly
slack:
  signing-secret: 70823e1769a2f1bd163ca53dc5386200
  client-id: 2518902811235.2555532277206
  client-secret: 37940eeb699e8cc1259d44533e587ee9
logging.level:
  com.slack.api: ERROR